"""date_migrate

Revision ID: 8563899bef6d
Revises: 1e0176b850b2
Create Date: 2021-01-31 18:20:11.452765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8563899bef6d'
down_revision = '1e0176b850b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('due_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'due_date')
    # ### end Alembic commands ###
